### ISSUE TITLE
separate client and server

### ISSUE THREAD

**Issue by mokhtarabadi** [genshen/wssocks#20]
I see the server and client is same, mean client have unused resources or maybe codes (!! I don't know and just think)  if you can, please separate the client from the server and remove status page resources (html, css, js) and other things from that
I just want to build the project and see the below error in yarn
`error An unexpected error occurred: "https://registry.yarnpkg.com/@typescript-eslint/eslint-plugin/-/eslint-plugin-2.24.0.tgz: Request failed \"404 Not Found\"".`
if you can make status page optional so can easily ignore that, I want to build this project for android but the size after build is about 9 Megabytes and after strip size changes to ~=6 Megabytes, I think if the can remove unused things in client side, can make it smaller than 6 Megabytes

thanks so much

**Comment by genshen** [comment]
From your description, are you expect to reduce binary size of client?   
In Go building, dependencies libs (including Go runtime) are all statically linked into binary. Even a [simple 'hello world' network program](https://gist.github.com/will3942/7793213) can have about 7.1 MiB (tested on linux).  
I think it's hard to make client binary size smaller than 6 Megabytes.  

---
In my tests, if we embed all status page resources (html, css, js, png) (about 2.9 MiB) into binary, the size of binaries is:
|  wssocks on different platforms | Size |
|--|--|
| wssocks-darwin-amd64 | 9.5M |
| wssocks-linux-amd64 | 9.5M |
| wssocks-linux-arm64 | 9.2M |
| wssocks-windows-amd64.exe | 9.5M |

Then I removed unused status page resources (*.map files, about 2 MiB), and only embed necessary status page resources files (only about 800.0 KiB) into binaries.  
The size of binaries is reduced, but they only reduced about 0.5 MiB:
|  wssocks on different platforms | Size |
|--|--|
| wssocks-darwin-amd64 | 9.0M |
| wssocks-linux-amd64 | 9.0M |
| wssocks-linux-arm64 | 8.7M |
| wssocks-windows-amd64.exe | 9.0M |

(Although I removed 2 MiB status page resources files, they only reduced about 0.5 MiB. This is because status page resources files is embed into binaries via gzip)

And last, I don't embed any status page resources into binary, their sizes are:
|  wssocks on different platforms | Size |
|--|--|
| wssocks-darwin-amd64 | 8.9 M |
| wssocks-linux-amd64 | 8.8 M |
| wssocks-linux-arm64 | 8.4 M |
| wssocks-windows-amd64.exe | 8.7 M |

With above tests, I found ***removing status page resources*** seems does not have a obvious improvement for reducing binary size.

I will try to separate client and server to see if this method can effectively reduce binaries' size (it needs some code changes).
